[project]
name = "svayam-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.2",
    "azure-cosmos>=4.14.2",
    "gradio>=5.23.1",
    "ijson>=3.4.0.post0",
    "langgraph-checkpoint-sqlite>=3.0.0",
    "nest-asyncio>=1.6.0",
    "openai>=2.8.1",
    "pyarrow>=22.0.0",
    "pydantic-core>=2.41.5",
    "python-dotenv>=1.2.1",
    "streamlit>=1.50.0",
    "tenacity>=9.1.2",
]
